<?php

/**
 * Globally registers the 'genericons' plugin
 */

/* !!!


IF YOU ARE EDITING THIS FILE, THEN YOU ARE EDITING A FILE THAT GETS OUTPUT FROM THE GENERICONS REPO!

https://github.com/Automattic/Genericons

DO NOT EDIT THIS FILE! 

If you need to edit this file, edit index-header.php and index-footer.php in the Genericons repo instead
OR if you're looking to change how SVGs get output, you'll need to edit strings in the Gruntfile :)

!!! */


function get_genericon( $genericon ) {
	$svg = "";

	switch ( $genericon ) {
