<?php

/**
 * Globally registers the 'genericons' plugin
 */

/* !!!


IF YOU ARE EDITING THIS FILE, THEN YOU ARE EDITING A FILE THAT GETS OUTPUT FROM THE GENERICONS REPO!

https://github.com/Automattic/Genericons

DO NOT EDIT THIS FILE! 

If you need to edit this file, edit index-header.php and index-footer.php in the Genericons repo instead
OR if you're looking to change how SVGs get output, you'll need to edit strings in the Gruntfile :)

!!! */


function get_genericon( $genericon ) {
	$svg = "";

	switch ( $genericon ) {
		case 'activity':
			$svg = '<svg class="genericon genericon-activity" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><style>.st0{fill:#231F20;}</style><path class="st0" d="M11 14.4L8.5 7.7l-2.4 5.7L3.9 9l-1.1 1.6-1.6-1.2L4.1 5l1.8 3.6 2.6-6.3L11 8.6l2.1-5.9 1.8.6z"/></g></svg>';
			break;
		case 'anchor':
			$svg = '<svg class="genericon genericon-anchor" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><style>.st0{fill:#0F0F0F;}</style><path class="st0" d="M12 8v2.5c0 .8-.7 1.5-1.5 1.5S9 11.3 9 10.5V5.8c.7-.3 1.1-1 1.1-1.8 0-1.1-.9-2-2-2s-2 .9-2 2c0 .7.4 1.3.9 1.7v4.8c0 .8-.7 1.5-1.5 1.5S4 11.3 4 10.5V8c-1.1 0-2 .9-2 2v.5C2 12.4 3.6 14 5.5 14c1 0 1.9-.4 2.5-1.1.6.6 1.5 1.1 2.5 1.1 1.9 0 3.5-1.6 3.5-3.5V10c0-1.1-.9-2-2-2z"/></g></svg>';
			break;
		case 'aside':
			$svg = '<svg class="genericon genericon-aside" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M12 2H4c-1.1 0-2 .9-2 2v8c0 1.1.9 2 2 2h6l4-4V4c0-1.1-.9-2-2-2zM9 7H4V6h5v1zm3-2H4V4h8v1z"/></g></svg>';
			break;
		case 'attachment':
			$svg = '<svg class="genericon genericon-attachment" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M9.5 1C8.1 1 7 2.2 7 3.5v7c0 .8.7 1.5 1.5 1.5s1.5-.7 1.5-1.5V5H9v5.5c0 .3-.2.5-.5.5s-.5-.2-.5-.5v-7C8 2.7 8.7 2 9.5 2s1.5.7 1.5 1.5v8c0 1.4-1.1 2.5-2.5 2.5S6 12.9 6 11.5V5H5v6.5C5 13.4 6.6 15 8.5 15s3.5-1.6 3.5-3.5v-8C12 2.2 10.9 1 9.5 1z"/></g></svg>';
			break;
		case 'audio':
			$svg = '<svg class="genericon genericon-audio" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M4 5c-1.1 0-2 .9-2 2v2c0 1.1.9 2 2 2h1l4 4V1L5 5H4zm7.5-.5l-.7.7c.8.7 1.2 1.7 1.2 2.8 0 1.1-.5 2.1-1.2 2.8l.7.7c.9-.9 1.5-2.1 1.5-3.5s-.6-2.6-1.5-3.5zM13 3l-.7.7C13.3 4.8 14 6.3 14 8c0 1.7-.7 3.2-1.8 4.2l.7.7c1.3-1.3 2.1-3 2.1-5 0-1.9-.8-3.6-2-4.9z"/></g></svg>';
			break;
		case 'bold':
			$svg = '<svg class="genericon genericon-bold" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M12 5c0-1.7-1.4-3-3-3H4v12h5c1.6 0 3-1.3 3-3v-1c0-.8-.3-1.5-.8-2 .5-.5.8-1.2.8-2V5zM6 4h3c.5 0 1 .5 1 1v1c0 .5-.5 1-1 1H6V4zm4 7c0 .5-.5 1-1 1H6V9h3c.5 0 1 .5 1 1v1z"/></g></svg>';
			break;
		case 'book':
			$svg = '<svg class="genericon genericon-book" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M12 1h-1v8l-1-1-1 1V1H3v14h9c.6 0 1-.4 1-1V2c0-.6-.4-1-1-1z"/></g></svg>';
			break;
		case 'bug':
			$svg = '<svg class="genericon genericon-bug" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M14.5 8H13c0-.485-.084-.946-.22-1.386C13.544 5.608 14 4.36 14 3v-.5c0-.276-.224-.5-.5-.5s-.5.224-.5.5V3c0 2.76-2.238 5-5 5-2.76 0-5-2.24-5-5v-.5c0-.276-.224-.5-.5-.5s-.5.224-.5.5V3c0 1.364.46 2.617 1.227 3.625C3.095 7.063 3 7.518 3 8H1.5c-.276 0-.5.224-.5.5s.224.5.5.5h1.6c.08.38.21.74.368 1.083C2.558 11.135 2 12.5 2 14v.5c0 .275.224.5.5.5s.5-.225.5-.5V14c0-1.132.386-2.166 1.02-3 .914 1.207 2.35 2 3.98 2 1.635 0 3.072-.796 3.984-2.01C12.62 11.83 13 12.87 13 14v.5c0 .275.224.5.5.5s.5-.225.5-.5V14c0-1.5-.556-2.866-1.467-3.917.158-.344.29-.702.366-1.083h1.6c.276 0 .5-.224.5-.5s-.224-.5-.5-.5zM8 7c1.633 0 3.034-.985 3.655-2.39C10.742 3.625 9.45 3 8 3c-1.448 0-2.742.625-3.655 1.61C4.965 6.015 6.368 7 8 7z"/></g></svg>';
			break;
		case 'cart':
			$svg = '<svg class="genericon genericon-cart" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M11 12c-.553 0-1 .447-1 1s.447 1 1 1 1-.447 1-1-.447-1-1-1zm-6 0c-.552 0-1 .447-1 1s.448 1 1 1 1-.447 1-1-.448-1-1-1zm7-3l2-5H5V2H2v1h2v8h8v-1H5V9h7z"/></g></svg>';
			break;
		case 'category':
			$svg = '<svg class="genericon genericon-category" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M5.5 7L5 8H4l1-2h5V5H6.5L6 4H3v8h8l2-5"/></g></svg>';
			break;
		case 'chat':
			$svg = '<svg class="genericon genericon-chat" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M13 4v3c0 1.654-1.346 3-3 3H6.914l-1 1H8.5l3.5 3.5V11h1c1.104 0 2-.896 2-2V6c0-1.104-.896-2-2-2z"/><path d="M10 2H2C.896 2 0 2.896 0 4v3c0 1.104.896 2 2 2h1v3.5L6.5 9H10c1.104 0 2-.896 2-2V4c0-1.104-.896-2-2-2z"/></g></svg>';
			break;
		case 'checkmark':
			$svg = '<svg class="genericon genericon-checkmark" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M11 4.25l-3.5 4-1.75-1.5-1 1L7 11h1l4-6"/></g></svg>';
			break;
		case 'close-alt':
			$svg = '<svg class="genericon genericon-close-alt" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M16 1l-1-1-6.5 6.5L2 0 1 1l6.5 6.5L1 14l1 1 6.5-6.5L15 15l1-1-6.5-6.5"/></g></svg>';
			break;
		case 'close':
			$svg = '<svg class="genericon genericon-close" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M12 5l-1-1-2.5 2.5L6 4 5 5l2.5 2.5L5 10l1 1 2.5-2.5L11 11l1-1-2.5-2.5"/></g></svg>';
			break;
		case 'cloud-download':
			$svg = '<svg class="genericon genericon-cloud-download" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M9 11H7v2H5l3 3 3-3H9v-2zm4-3h-.184c.112-.314.184-.647.184-1 0-1.657-1.344-3-3-3-1.208 0-2.244.72-2.72 1.75C6.83 5.286 6.2 5 5.5 5 4.12 5 3 6.12 3 7.5c0 .17.018.338.05.5H3c-1.104 0-2 .896-2 2s.896 2 2 2h3v-2h4v2h3c1.104 0 2-.896 2-2s-.896-2-2-2z"/></g></svg>';
			break;
		case 'cloud-upload':
			$svg = '<svg class="genericon genericon-cloud-upload" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M13 8h-.184c.112-.314.184-.647.184-1 0-1.657-1.344-3-3-3-1.208 0-2.244.72-2.72 1.75C6.83 5.286 6.2 5 5.5 5 4.12 5 3 6.12 3 7.5c0 .17.018.338.05.5H3c-1.104 0-2 .896-2 2s.896 2 2 2h4v-2H5l3-3 3 3H9v2h4c1.104 0 2-.896 2-2s-.896-2-2-2z"/></g></svg>';
			break;
		case 'cloud':
			$svg = '<svg class="genericon genericon-cloud" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M13 8h-.184c.112-.314.184-.647.184-1 0-1.657-1.344-3-3-3-1.208 0-2.244.72-2.72 1.75C6.83 5.287 6.2 5 5.5 5 4.12 5 3 6.12 3 7.5c0 .172.017.337.05.5H3c-1.104 0-2 .896-2 2s.896 2 2 2h10c1.104 0 2-.896 2-2s-.896-2-2-2z"/></g></svg>';
			break;
		case 'code':
			$svg = '<svg class="genericon genericon-code" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path stroke="#231F20" stroke-width="2" stroke-miterlimit="10" d="M4 5L2 8l2 3M12 5l2 3-2 3M7 12l2-8"/></g></svg>';
			break;
		case 'cog':
			$svg = '<svg class="genericon genericon-cog" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M14.75 10.156l-1.81-1.568C12.964 8.393 13 8.2 13 8c0-.203-.036-.395-.06-.59l1.81-1.57-.45-1.087-2.387.17c-.246-.313-.525-.592-.837-.837l.17-2.386-1.087-.45-1.57 1.81C8.393 3.037 8.2 3 8 3s-.394.037-.59.06L5.84 1.25l-1.086.45.17 2.386c-.313.246-.592.526-.838.838L1.7 4.754l-.45 1.09 1.81 1.57C3.035 7.607 3 7.798 3 8c0 .203.036.396.06.592l-1.81 1.57.45 1.087 2.388-.17c.246.31.524.59.836.834l-.17 2.386 1.09.45 1.57-1.81c.194.024.385.06.586.06.203 0 .396-.036.593-.06l1.568 1.81 1.09-.45-.17-2.388c.31-.245.59-.524.834-.836l2.386.17.45-1.09zM10 8c0 1.104-.896 2-2 2s-2-.896-2-2 .896-2 2-2 2 .896 2 2z"/></g></svg>';
			break;
		case 'collapse':
			$svg = '<svg class="genericon genericon-collapse" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M11 11L7.5 7.5 4 11l-1-1 4.5-4.5L12 10"/></g></svg>';
			break;
		case 'comment':
			$svg = '<svg class="genericon genericon-comment" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M12 4H4c-1.104 0-2 .896-2 2v3c0 1.104.896 2 2 2h1v3.5L8.5 11H12c1.104 0 2-.896 2-2V6c0-1.104-.896-2-2-2z"/></g></svg>';
			break;
		case 'day':
			$svg = '<svg class="genericon genericon-day" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M11 3V2h-1v1H5V2H4v1H2v10h11V3h-2zm1 8c0 .553-.447 1-1 1H4c-.552 0-1-.447-1-1V6c0-.553.448-1 1-1h7c.553 0 1 .447 1 1v5zM7.5 6h-1c-.276 0-.5.224-.5.5s.224.5.5.5H7v3.5c0 .276.224.5.5.5s.5-.224.5-.5v-4c0-.276-.224-.5-.5-.5z"/></g></svg>';
			break;
		case 'document':
			$svg = '<svg class="genericon genericon-document" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M9 3H4v10h8V6L9 3zm2 9H5V4h3v3h3v5z"/></g></svg>';
			break;
		case 'download':
			$svg = '<svg class="genericon genericon-download" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M11 7H9V3H7v4H5l3 3 3-3zm-8 4v2h10v-2H3z"/></g></svg>';
			break;
		case 'edit':
			$svg = '<svg class="genericon genericon-edit" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M10 2.5l-7 7V13h3.5l7-7L10 2.5zM10 4l.75.75-4.646 4.646-.75-.75L10 4zm-4 8l-2-2 1-1 .75.75.5.5L7 11l-1 1zm.604-2.104L11.25 5.25 12 6l-4.646 4.646-.75-.75z"/></g></svg>';
			break;
		case 'ellipsis':
			$svg = '<svg class="genericon genericon-ellipsis" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M3 6.25c-.967 0-1.75.783-1.75 1.75 0 .966.783 1.75 1.75 1.75S4.75 8.966 4.75 8c0-.967-.783-1.75-1.75-1.75zm5 0c-.967 0-1.75.783-1.75 1.75 0 .966.783 1.75 1.75 1.75.966 0 1.75-.784 1.75-1.75 0-.967-.784-1.75-1.75-1.75zm5 0c-.966 0-1.75.783-1.75 1.75 0 .966.784 1.75 1.75 1.75s1.75-.784 1.75-1.75c0-.967-.784-1.75-1.75-1.75z"/></g></svg>';
			break;
		case 'expand':
			$svg = '<svg class="genericon genericon-expand" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M11 6L7.5 9.5 4 6 3 7l4.5 4.5L12 7"/></g></svg>';
			break;
		case 'external':
			$svg = '<svg class="genericon genericon-external" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M10 11H5V6h2l1-1H4v7h7V8l-1 1v2zM8 3v1h3.293L7 8.293 7.707 9 12 4.707V8h1V3H8z"/></g></svg>';
			break;
		case 'fastforward':
			$svg = '<svg class="genericon genericon-fastforward" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M15 8L7 3v3.75L1 3v10l6-3.75V13"/></g></svg>';
			break;
		case 'feed':
			$svg = '<svg class="genericon genericon-feed" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M2 6v2c3.31 0 6 2.69 6 6h2c0-4.418-3.582-8-8-8zm0-4v2c5.514 0 10 4.486 10 10h2C14 7.373 8.627 2 2 2zm1.5 9c-.83 0-1.5.672-1.5 1.5S2.67 14 3.5 14 5 13.328 5 12.5 4.33 11 3.5 11z"/></g></svg>';
			break;
		case 'flag':
			$svg = '<svg class="genericon genericon-flag" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M2 14h2V2H2v12zM12 3c-2 0-2-1-4-1S6 3 5 3v6c1 0 1-1 3-1s2 1 4 1h2V3h-2z"/></g></svg>';
			break;
		case 'fullscreen':
			$svg = '<svg class="genericon genericon-fullscreen" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M1 5V2h3M5 6h6v4H5zM12 2h3v3M1 11v3h3M12 14h3v-3"/><path d="M12 5l2-3 1 1M12 11l3 2-1 1M1 13l3-2-2 3M1 3l1-1 2 3"/></g></svg>';
			break;
		case 'gallery':
			$svg = '<svg class="genericon genericon-gallery" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M9 5v7h7V5H9zM1 8h7V5H1v3zm4 4h3V9H5v3zm-4 0h3V9H1v3z"/></g></svg>';
			break;
		case 'heart':
			$svg = '<svg class="genericon genericon-heart" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M8 13L2.94 8.21c-1.166-1.103-1.26-2.993-.21-4.22 1.05-1.228 2.846-1.327 4.013-.223L8 4.957l1.256-1.19c1.166-1.103 2.964-1.005 4.014.223 1.052 1.227.956 3.117-.21 4.222L8 13z"/></g></svg>';
			break;
		case 'help':
			$svg = '<svg class="genericon genericon-help" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M8 2C4.686 2 2 4.687 2 8s2.686 6 6 6c3.313 0 6-2.687 6-6s-2.687-6-6-6zm0 10c-.553 0-1-.45-1-1s.447-1 1-1c.552 0 1 .45 1 1s-.448 1-1 1zm2.49-5.03c-.197.306-.506.594-.936.866-.36.234-.585.406-.68.516-.09.107-.134.236-.134.382V9H7.15v-.445c0-.336.068-.623.205-.855.14-.234.384-.46.737-.68.28-.176.478-.335.603-.476.12-.142.184-.304.184-.486 0-.145-.065-.26-.2-.344-.13-.085-.3-.127-.51-.127-.522 0-1.13.185-1.828.554l-.718-1.406C6.482 4.244 7.378 4 8.314 4c.768 0 1.375.168 1.812.506.438.337.654.798.654 1.38 0 .42-.096.78-.29 1.084z"/></g></svg>';
			break;
		case 'hide':
			$svg = '<svg class="genericon genericon-hide" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><g><path d="M8 11c1.656 0 3-1.344 3-3 0-.155-.02-.305-.044-.452l-3.408 3.408c.147.025.297.044.452.044z"/><path d="M13.252 5.252l-1.06 1.06L13.878 8l-2.908 2.908c-.79.807-1.846 1.25-2.97 1.25-.485 0-.948-.104-1.39-.265L5.46 13.04c.765.39 1.622.62 2.538.62 1.583 0 3.015-.653 4.042-1.702L16 8l-2.748-2.748zM12.547 2.546L11.5 3.593C10.535 2.823 9.33 2.34 8 2.34c-1.585 0-3.016.653-4.043 1.703L0 8l3.546 3.546-1 1 1.007 1.007 10-10-1.006-1.007zM7 8c-.553 0-1-.448-1-1s.447-1 1-1c.552 0 1 .448 1 1s-.448 1-1 1zm2.603-2.51C9.14 5.19 8.596 5 8 5 6.344 5 5 6.343 5 8c0 .596.19 1.14.49 1.604l-.882.883L2.122 8 5.03 5.093C5.82 4.285 6.873 3.84 8 3.84c.89 0 1.72.302 2.43.824l-.827.826z"/></g></g></svg>';
			break;
		case 'hierarchy':
			$svg = '<svg class="genericon genericon-hierarchy" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M2 5h2V3H2v2zm4-2v2h8V3H6zM2 9h2V7H2v2zm9-2H6v2h5V7zm-9 6h2v-2H2v2zm4 0h7v-2H6v2z"/></g></svg>';
			break;
		case 'home':
			$svg = '<svg class="genericon genericon-home" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M8 3L3 7l1 1v4h8V8l1-1-5-4zm1 8.5H7V8h2v3.5z"/></g></svg>';
			break;
		case 'image':
			$svg = '<svg class="genericon genericon-image" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M11 5l-1-2H6L5 5 1 6v7h14V6l-4-1zm-3 6.998c-1.933 0-3.5-1.566-3.5-3.5 0-1.933 1.567-3.5 3.5-3.5 1.934 0 3.5 1.567 3.5 3.5 0 1.934-1.566 3.5-3.5 3.5zM4 3.5H2v1.25l2-.5V3.5zM8 6C6.62 6 5.5 7.117 5.5 8.5 5.5 9.88 6.62 11 8 11s2.5-1.12 2.5-2.5C10.5 7.117 9.38 6 8 6z"/></g></svg>';
			break;
		case 'info':
			$svg = '<svg class="genericon genericon-info" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M8 2C4.686 2 2 4.687 2 8s2.686 6 6 6c3.313 0 6-2.687 6-6s-2.687-6-6-6zm0 2c.552 0 1 .448 1 1s-.448 1-1 1c-.553 0-1-.448-1-1s.447-1 1-1zm2 8H6v-1h1.25V8h-1V7h2.5v4H10v1z"/></g></svg>';
			break;
		case 'italic':
			$svg = '<svg class="genericon genericon-italic" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M10.688 5L11 4H7.5l-.312 1h1l-1.876 6h-1L5 12h3.5l.312-1h-1l1.876-6"/></g></svg>';
			break;
		case 'key':
			$svg = '<svg class="genericon genericon-key" height="16" width="16" xmlns="http://<g>www.w3.org/2000/svg" width="15.998" height="15.998" viewBox="0 0 15.998 15.998"><path d="M13.418 4.78l-2.23-2.23c-.777-.78-2.04-.78-2.82 0L6.55 4.37c-.777.777-.777 2.04 0 2.82l.007.005L3 10.75v2.248h2.25L8.807 9.44c.78.755 2.022.75 2.792-.02l1.818-1.82c.78-.78.78-2.042 0-2.82zm-2.92 2.594l-2-2 1.25-1.25 2 2-1.25 1.25z"/></g></svg>';
			break;
		case 'link':
			$svg = '<svg class="genericon genericon-link" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M8.5 2C7.12 2 6 3.12 6 4.5v3c0 1.025.618 1.903 1.5 2.29V8.61C7.195 8.335 7 7.94 7 7.5v-3C7 3.673 7.673 3 8.5 3s1.5.673 1.5 1.5v3c0 .44-.195.835-.5 1.11v1.18c.883-.387 1.5-1.265 1.5-2.29v-3C11 3.12 9.88 2 8.5 2z"/><path d="M7.5 5.21v1.18c.305.275.5.67.5 1.11v3c0 .827-.673 1.5-1.5 1.5S5 11.327 5 10.5v-3c0-.44.195-.835.5-1.11V5.21C4.618 5.598 4 6.476 4 7.5v3C4 11.88 5.12 13 6.5 13S9 11.88 9 10.5v-3c0-1.025-.618-1.903-1.5-2.29z"/></g></svg>';
			break;
		case 'location':
			$svg = '<svg class="genericon genericon-location" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M7.5 2C5.015 2 3 4.015 3 6.5c0 1.244.505 2.37 1.32 3.185l3.18 3.18 3.18-3.18C11.494 8.87 12 7.745 12 6.5 12 4.015 9.985 2 7.5 2zm0 7C6.12 9 5 7.88 5 6.5S6.12 4 7.5 4 10 5.12 10 6.5 8.88 9 7.5 9z"/></g></svg>';
			break;
		case 'lock':
			$svg = '<svg class="genericon genericon-lock" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M12 7V6c0-2.21-1.79-4-4-4S4 3.79 4 6v1c-.552 0-1 .448-1 1v5c0 .553.448 1 1 1h8c.553 0 1-.447 1-1V8c0-.552-.447-1-1-1zM6 7V6c0-1.104.896-2 2-2s2 .896 2 2v1H6z"/></g></svg>';
			break;
		case 'mail':
			$svg = '<svg class="genericon genericon-mail" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M2 4v1l6 3 6-3V4H2zm0 2.5V12h12V6.5l-6 3-6-3z"/></g></svg>';
			break;
		case 'menu':
			$svg = '<svg class="genericon genericon-menu" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M0 14h16v-2H0v2zM0 2v2h16V2H0zm0 7h16V7H0v2z"/></g></svg>';
			break;
		case 'microphone':
			$svg = '<svg class="genericon genericon-microphone" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M8 9c.83 0 1.5-.672 1.5-1.5v-4C9.5 2.673 8.83 2 8 2c-.827 0-1.5.673-1.5 1.5v4C6.5 8.328 7.173 9 8 9zm2.95-1c-.24 1.418-1.464 2.5-2.95 2.5-1.484 0-2.71-1.082-2.95-2.5h-1.5c.215 1.91 1.615 3.453 3.45 3.875V14h2v-2.125c1.836-.422 3.235-1.965 3.45-3.875h-1.5z"/></g></svg>';
			break;
		case 'minus':
			$svg = '<svg class="genericon genericon-minus" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M3 7h10v2H3z"/></g></svg>';
			break;
		case 'month':
			$svg = '<svg class="genericon genericon-month" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M6 11h1v-1H6v1zm0-2h1V8H6v1zm0-2h1V6H6v1zm-2 4h1v-1H4v1zm0-2h1V8H4v1zm6 0h1V8h-1v1zM8 7h1V6H8v1zm2 0h1V6h-1v1zm1-4V2h-1v1H5V2H4v1H2v10h11V3h-2zm1 8c0 .553-.447 1-1 1H4c-.552 0-1-.447-1-1V6c0-.553.448-1 1-1h7c.553 0 1 .447 1 1v5zM8 9h1V8H8v1zm0 2h1v-1H8v1z"/></g></svg>';
			break;
		case 'move':
			$svg = '<svg class="genericon genericon-move" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M15 8l-3-3v2H9V4h2L8 1 5 4h2v3H4V5L1 8l3 3V9h3v3H5l3 3 3-3H9V9h3v2"/></g></svg>';
			break;
		case 'next':
			$svg = '<svg class="genericon genericon-next" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M8 4.646l-.677.677L10 8H3v1h7l-2.677 2.677.677.677L11.854 8.5"/></g></svg>';
			break;
		case 'notice':
			$svg = '<svg class="genericon genericon-notice" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M8 2C4.686 2 2 4.687 2 8s2.686 6 6 6c3.313 0 6-2.687 6-6s-2.687-6-6-6zm0 10c-.552 0-1-.447-1-1s.448-1 1-1c.553 0 1 .447 1 1s-.447 1-1 1zm.697-3H7.3l-.4-5h2.2l-.403 5z"/></g></svg>';
			break;
		case 'paintbrush':
			$svg = '<svg class="genericon genericon-paintbrush" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><g><path d="M6 1c0 2-1 3-1 3l.01.02L2.722 6.31c-.39.39-.39 1.025 0 1.414l2.1 2.102 5-5L6 1zM13.58 11.58L11 9h-1l-.5-.5c-.275-.275-.182-.818.207-1.207l.586-.586c.39-.39.39-1.025 0-1.414l-.116-.116-5 5 .116.116c.39.39 1.025.39 1.414 0l.586-.586c.39-.39.932-.482 1.207-.207l.5.5v1l2.58 2.58c.257.26.61.42 1.005.42.78 0 1.415-.634 1.415-1.415 0-.394-.16-.75-.42-1.005zm-.995 1.505c-.276 0-.5-.224-.5-.5s.224-.5.5-.5.5.224.5.5-.224.5-.5.5z"/></g></g></svg>';
			break;
		case 'pause':
			$svg = '<svg class="genericon genericon-pause" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M4 13h3V3H4v10zM9 3v10h3V3H9z"/></g></svg>';
			break;
		case 'phone':
			$svg = '<svg class="genericon genericon-phone" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M10 2H6c-1.104 0-2 .896-2 2v8c0 1.104.896 2 2 2h4c1.104 0 2-.896 2-2V4c0-1.104-.896-2-2-2zM8 13c-.552 0-1-.447-1-1s.448-1 1-1c.553 0 1 .447 1 1s-.447 1-1 1zm3-3H5V4h6v6z"/></g></svg>';
			break;
		case 'picture':
			$svg = '<svg class="genericon genericon-picture" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M3 3v10h10V3H3zm3 2c.552 0 1 .448 1 1s-.448 1-1 1-1-.448-1-1 .448-1 1-1zm6 7H4l2-3 1.5 2.25L11 6l1 1.5V12z"/></g></svg>';
			break;
		case 'pinned':
			$svg = '<svg class="genericon genericon-pinned" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M3.732 11.56c-.783.784-.904 1.19-1.06 1.77.577-.157.984-.278 1.767-1.062l4.24-4.242-.705-.708-4.243 4.243z"/><path d="M9.293 2.464c.39.39.39 1.023 0 1.414L7.88 5.293c-.392.39-1.025.39-1.416 0L5.05 6.707l4.243 4.242 1.414-1.415c-.39-.39-.39-1.023 0-1.414l1.414-1.413c.392-.39 1.024-.39 1.415 0l1.414-1.414-4.243-4.243-1.414 1.414z"/></g></svg>';
			break;
		case 'play':
			$svg = '<svg class="genericon genericon-play" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M4 3v10l8-5"/></g></svg>';
			break;
		case 'plugin':
			$svg = '<svg class="genericon genericon-plugin" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M7 3c0-.553-.448-1-1-1s-1 .447-1 1v3h2V3zm4 0c0-.553-.447-1-1-1s-1 .447-1 1v3h2V3zM3 7c0 2.42 1.718 4.436 4 4.9V14h2v-2.1c2.282-.465 4-2.48 4-4.9H3z"/></g></svg>';
			break;
		case 'plus':
			$svg = '<svg class="genericon genericon-plus" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M13 7H9V3H7v4H3v2h4v4h2V9h4"/></g></svg>';
			break;
		case 'previous':
			$svg = '<svg class="genericon genericon-previous" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M8 4.646l.677.677L6 8h7v1H6l2.677 2.677-.677.677L4.146 8.5"/></g></svg>';
			break;
		case 'print':
			$svg = '<svg class="genericon genericon-print" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M2 6v6h2V9h8v3h2V6H2zm9-3H5v2h6V3zm0 8v-1H5v1c0 .768.293 1.535.88 2.12l.878.88h6l-.88-.88C11.294 12.536 11 11.77 11 11z"/></g></svg>';
			break;
		case 'quote':
			$svg = '<svg class="genericon genericon-quote" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M2 9h3c0 1.104-.896 2-2 2v2c2.21 0 4-1.79 4-4V4H2v5zm7-5v5h3c0 1.104-.896 2-2 2v2c2.21 0 4-1.79 4-4V4H9z"/></g></svg>';
			break;
		case 'refresh':
			$svg = '<svg class="genericon genericon-refresh" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M3.775 3.775C2.688 4.86 2 6.343 2 8c0 2.972 2.164 5.433 5 5.91v-2.052C5.278 11.412 4 9.86 4 8c0-1.105.458-2.095 1.185-2.815L7 7V2H2l1.775 1.775zM14 8c0-2.972-2.164-5.433-5-5.91v2.052c1.722.446 3 1.997 3 3.858 0 1.105-.458 2.095-1.185 2.815l-1.67-1.67L9 9v5h5l-1.775-1.775C13.312 11.14 14 9.657 14 8z"/></g></svg>';
			break;
		case 'reply':
			$svg = '<svg class="genericon genericon-reply" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M10 6H8V3L3 8l5 5v-3h2c1.023 0 2.047.39 2.828 1.172L14 12.342V10c0-2.21-1.79-4-4-4z"/></g></svg>';
			break;
		case 'rewind':
			$svg = '<svg class="genericon genericon-rewind" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M15 3L9 6.75V3L1 8l8 5V9.25L15 13"/></g></svg>';
			break;
		case 'search':
			$svg = '<svg class="genericon genericon-search" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M14 13l-3.866-3.866c.54-.74.866-1.647.866-2.634C11 4.015 8.985 2 6.5 2S2 4.015 2 6.5 4.015 11 6.5 11c.987 0 1.893-.327 2.634-.866L13 14l1-1zM3 6.5C3 4.567 4.567 3 6.5 3 8.434 3 10 4.567 10 6.5S8.434 10 6.5 10C4.567 10 3 8.433 3 6.5z"/></g></svg>';
			break;
		case 'send-to-phone':
			$svg = '<svg class="genericon genericon-send-to-phone" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M10 2H6c-1.104 0-2 .896-2 2v1h1V4h6v6H5V9H4v3c0 1.104.896 2 2 2h4c1.104 0 2-.896 2-2V4c0-1.104-.896-2-2-2zM8 13c-.552 0-1-.447-1-1s.448-1 1-1c.553 0 1 .447 1 1s-.447 1-1 1zM6 9l3-2-3-2v1H2v2h4v1z"/></g></svg>';
			break;
		case 'send-to-tablet':
			$svg = '<svg class="genericon genericon-send-to-tablet" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M5 9l3-2-3-2v1H1v2h4v1zm7-9H4C2.896 0 2 .896 2 2v3h2V2h8v10H4V9H2v5c0 1.104.896 2 2 2h8c1.104 0 2-.896 2-2V2c0-1.104-.896-2-2-2zM8 15c-.552 0-1-.447-1-1s.448-1 1-1c.553 0 1 .447 1 1s-.447 1-1 1z"/></g></svg>';
			break;
		case 'share':
			$svg = '<svg class="genericon genericon-share" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M11 8c0 1.657-1.343 3-3 3-.828 0-1.563-.35-2.105-.895-.39-.392-1.023-.39-1.414 0s-.39 1.023 0 1.414l-.004.004C5.38 12.43 6.62 13 8 13c2.05 0 3.806-1.235 4.578-3H15V8h-4zM8 5c.83 0 1.563.35 2.105.895l.005-.005c.39.39 1.023.39 1.414 0s.39-1.023 0-1.414C10.62 3.57 9.382 3 8 3 5.95 3 4.194 4.235 3.422 6H1v2h4c0-1.657 1.343-3 3-3zM6.5 8c0 .83.672 1.5 1.5 1.5.83 0 1.5-.67 1.5-1.5S8.83 6.5 8 6.5c-.828 0-1.5.67-1.5 1.5z"/></g></svg>';
			break;
		case 'show':
			$svg = '<svg class="genericon genericon-show" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M12.042 4.042C11.015 2.992 9.584 2.34 8 2.34c-1.585 0-3.016.653-4.043 1.703L0 8l3.957 3.956C4.984 13.006 6.417 13.66 8 13.66c1.583 0 3.015-.653 4.042-1.702L16 8l-3.958-3.958zm-1.07 6.866c-.79.807-1.846 1.25-2.97 1.25-1.127 0-2.183-.443-2.984-1.263L2.122 8 5.03 5.093C5.82 4.285 6.873 3.84 8 3.84c1.125 0 2.18.444 2.98 1.262L13.88 8l-2.908 2.908zM5 8c0 1.656 1.344 3 3 3s3-1.344 3-3c0-1.657-1.344-3-3-3S5 6.343 5 8m1-1c0-.552.447-1 1-1 .552 0 1 .448 1 1s-.448 1-1 1c-.553 0-1-.448-1-1z"/></g></svg>';
			break;
		case 'shuffle':
			$svg = '<svg class="genericon genericon-shuffle" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M13 10h-2c-1.104 0-2-.896-2-2 0-2.21-1.79-4-4-4H2v2h3c1.104 0 2 .896 2 2 0 2.21 1.79 4 4 4h2v1l2-2-2-2v1zm-2-4h2v1l2-2-2-2v1h-2c-.843 0-1.622.263-2.267.708.447.506.786 1.1 1 1.756C10.08 6.18 10.517 6 11 6zm-6 4H2v2h3c.843 0 1.622-.264 2.267-.708-.447-.506-.786-1.1-1-1.756C5.92 9.82 5.483 10 5 10z"/></g></svg>';
			break;
		case 'sitemap':
			$svg = '<svg class="genericon genericon-sitemap" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M14 11.277V10c0-1.657-1.344-3-3-3H9V4.723c.596-.347 1-.985 1-1.723 0-1.104-.896-2-2-2s-2 .896-2 2c0 .738.405 1.376 1 1.723V7H5c-1.657 0-3 1.343-3 3v1.277c-.595.347-1 .985-1 1.723 0 1.104.896 2 2 2s2-.896 2-2c0-.738-.405-1.376-1-1.723V10c0-.553.448-1 1-1h2v2.277c-.595.347-1 .985-1 1.723 0 1.104.896 2 2 2s2-.896 2-2c0-.738-.404-1.376-1-1.723V9h2c.553 0 1 .447 1 1v1.277c-.596.347-1 .984-1 1.723 0 1.104.896 2 2 2s2-.896 2-2c0-.738-.404-1.376-1-1.723zM8 2c.552 0 1 .448 1 1s-.448 1-1 1-1-.448-1-1 .448-1 1-1zM3 14c-.552 0-1-.447-1-1s.448-1 1-1 1 .447 1 1-.448 1-1 1zm5 0c-.552 0-1-.447-1-1s.448-1 1-1 1 .447 1 1-.448 1-1 1zm5 0c-.553 0-1-.447-1-1s.447-1 1-1 1 .447 1 1-.447 1-1 1z"/></g></svg>';
			break;
		case 'skip-ahead':
			$svg = '<svg class="genericon genericon-skip-ahead" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M2 13l8-5-8-5v10zm9-10v10h3V3h-3z"/></g></svg>';
			break;
		case 'skip-back':
			$svg = '<svg class="genericon genericon-skip-back" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M6 8l8 5V3L6 8zm-4 5h3V3H2v10z"/></g></svg>';
			break;
		case 'spam':
			$svg = '<svg class="genericon genericon-spam" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M11 2H5L2 5v6l3 3h6l3-3V5l-3-3zM8 12c-.552 0-1-.447-1-1s.448-1 1-1c.553 0 1 .447 1 1s-.447 1-1 1zm.697-3H7.3l-.4-5h2.2l-.403 5z"/></g></svg>';
			break;
		case 'standard':
			$svg = '<svg class="genericon genericon-standard" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M4 5v1h8V5H4zm5 2H4v1h5V7zm1 1h2V7h-2v1zm-3 2h5V9H7v1zM6 9H4v1h2V9zm-2 3h6v-1H4v1z"/></g></svg>';
			break;
		case 'star-empty':
			$svg = '<svg class="genericon genericon-star-empty" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M8 4.2L8.922 7h2.902L9.478 8.64l.925 2.762L8 9.69 5.6 11.4l.923-2.76L4.177 7h2.9L8 4.2M8 1L6.354 6H1l4.338 3.03L3.674 14 8 10.918 12.326 14l-1.663-4.97L15 6H9.646L8 1z"/></g></svg>';
			break;
		case 'star-half':
			$svg = '<svg class="genericon genericon-star-half" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M15 6H9.646L8 1 6.354 6H1l4.338 3.03L3.674 14 8 10.918 12.326 14l-1.663-4.97L15 6zM8 9.69V4.2L8.922 7h2.902L9.478 8.64l.925 2.762L8 9.69z"/></g></svg>';
			break;
		case 'star':
			$svg = '<svg class="genericon genericon-star" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M15 6H9.646L8 1 6.354 6H1l4.338 3.03L3.674 14 8 10.918 12.326 14l-1.663-4.97"/></g></svg>';
			break;
		case 'status':
			$svg = '<svg class="genericon genericon-status" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M11 5c0-1.657-1.344-3-3-3-1.657 0-3 1.343-3 3 0 1.305.837 2.403 2 2.816V13l2-1V7.816c1.162-.413 2-1.51 2-2.816z"/></g></svg>';
			break;
		case 'stop':
			$svg = '<svg class="genericon genericon-stop" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M4 4h8v8H4z"/></g></svg>';
			break;
		case 'subscribe':
			$svg = '<svg class="genericon genericon-subscribe" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M12 5V4H0v1l6 3 6-3zM0 6.5V12h8V8.5l-2 1-6-3zM15 7h-5c-.553 0-1 .448-1 1v5c0 .553.447 1 1 1h5c.553 0 1-.447 1-1V8c0-.552-.447-1-1-1zm0 4h-2v2h-1v-2h-2v-1h2V8h1v2h2v1z"/></g></svg>';
			break;
		case 'subscribed':
			$svg = '<svg class="genericon genericon-subscribed" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><g><path d="M12 5V4H0v1l6 3"/><path d="M0 6.5V12h8V8.5l-2 1M15 7h-5c-.553 0-1 .448-1 1v5c0 .553.447 1 1 1h5c.553 0 1-.447 1-1V8c0-.552-.447-1-1-1zm-3.035 6l-2.12-2.12.706-.708 1.415 1.414 2.828-2.828.707.707L11.965 13z"/></g></g></svg>';
			break;
		case 'summary':
			$svg = '<svg class="genericon genericon-summary" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M5.5 8c-.276 0-.5.224-.5.5s.224.5.5.5.5-.224.5-.5-.224-.5-.5-.5zm0-2c-.276 0-.5.224-.5.5s.224.5.5.5.5-.224.5-.5-.224-.5-.5-.5zm0 4c-.276 0-.5.224-.5.5s.224.5.5.5.5-.224.5-.5-.224-.5-.5-.5zM7 9h3V8H7v1zm0 2h3v-1H7v1zm3-8c0-.553-.447-1-1-1H6c-.552 0-1 .447-1 1H3v10h9V3h-2zM6.5 3h2c.276 0 .5.224.5.5s-.224.5-.5.5h-2c-.276 0-.5-.224-.5-.5s.224-.5.5-.5zm4.5 9H4V4h1v1h5V4h1v8zM7 7h3V6H7v1z"/></g></svg>';
			break;
		case 'tablet':
			$svg = '<svg class="genericon genericon-tablet" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M12 0H4C2.896 0 2 .896 2 2v12c0 1.104.896 2 2 2h8c1.104 0 2-.896 2-2V2c0-1.104-.896-2-2-2zM8 15c-.552 0-1-.447-1-1s.448-1 1-1c.553 0 1 .447 1 1s-.447 1-1 1zm4-3H4V2h8v10z"/></g></svg>';
			break;
		case 'tag':
			$svg = '<svg class="genericon genericon-tag" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M8 4l-6 6 4 4 6-6V4H8zm2 3c-.553 0-1-.447-1-1s.447-1 1-1 1 .447 1 1-.447 1-1 1z"/></g></svg>';
			break;
		case 'time':
			$svg = '<svg class="genericon genericon-time" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M7.5 2C4.462 2 2 4.462 2 7.5 2 10.537 4.462 13 7.5 13c3.037 0 5.5-2.463 5.5-5.5C13 4.462 10.537 2 7.5 2zm0 10C5.015 12 3 9.985 3 7.5S5.015 3 7.5 3C9.984 3 12 5.015 12 7.5S9.984 12 7.5 12zM8 4H7v3.707l2.62 2.62.708-.706L8 7.294V4z"/></g></svg>';
			break;
		case 'top':
			$svg = '<svg class="genericon genericon-top" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M3 12h10L8 7l-5 5zm0-7v1h10V5H3z"/></g></svg>';
			break;
		case 'trash':
			$svg = '<svg class="genericon genericon-trash" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M10 4c0-.553-.447-1-1-1H6c-.552 0-1 .447-1 1L3 5v1h9V5l-2-1zM8.5 5h-2c-.276 0-.5-.224-.5-.5s.224-.5.5-.5h2c.276 0 .5.224.5.5s-.224.5-.5.5zM10 6.5V12H9V6.5H8V12H7V6.5H6V12H5V6.5H4V12c0 .553.448 1 1 1h5c.553 0 1-.447 1-1V6.5h-1z"/></g></svg>';
			break;
		case 'unapprove':
			$svg = '<svg class="genericon genericon-unapprove" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M8 2C4.687 2 2 4.687 2 8s2.687 6 6 6 6-2.687 6-6-2.687-6-6-6zm4 6c0 .74-.215 1.426-.565 2.02L5.98 4.567C6.573 4.216 7.26 4 8 4c2.21 0 4 1.79 4 4zM4 8c0-.74.215-1.425.565-2.02l5.455 5.455C9.425 11.785 8.74 12 8 12c-2.21 0-4-1.79-4-4z"/></g></svg>';
			break;
		case 'unsubscribe':
			$svg = '<svg class="genericon genericon-unsubscribe" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M12 5V4H0v1l6 3 6-3zM0 6.5V12h8V8.5l-2 1-6-3zM15 7h-5c-.553 0-1 .448-1 1v5c0 .553.447 1 1 1h5c.553 0 1-.447 1-1V8c0-.552-.447-1-1-1zm0 4h-5v-1h5v1z"/></g></svg>';
			break;
		case 'unzoom':
			$svg = '<svg class="genericon genericon-unzoom" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M10.134 9.134c.54-.74.866-1.647.866-2.634C11 4.015 8.985 2 6.5 2S2 4.015 2 6.5 4.015 11 6.5 11c.987 0 1.893-.327 2.634-.866L13 14l1-1-3.866-3.866zM6.5 10C4.567 10 3 8.433 3 6.5S4.567 3 6.5 3C8.434 3 10 4.567 10 6.5S8.434 10 6.5 10zM4 7h5V6H4v1z"/></g></svg>';
			break;
		case 'user':
			$svg = '<svg class="genericon genericon-user" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M8 7c1.104 0 2-.896 2-2s-.896-2-2-2-2 .896-2 2 .896 2 2 2zm1 1H7c-1.656 0-3 1.343-3 3v2h8v-2c0-1.657-1.344-3-3-3z"/></g></svg>';
			break;
		case 'video':
			$svg = '<svg class="genericon genericon-video" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M4 3v10l9-5"/></g></svg>';
			break;
		case 'videocamera':
			$svg = '<svg class="genericon genericon-videocamera" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M11 7V5c0-.552-.447-1-1-1H3c-.552 0-1 .448-1 1v6c0 .553.448 1 1 1h7c.553 0 1-.447 1-1V9l3 3V4l-3 3z"/></g></svg>';
			break;
		case 'warning':
			$svg = '<svg class="genericon genericon-warning" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M15.594 11.297L9.66 1.633c-.913-1.487-2.407-1.487-3.32 0L.406 11.297C-.508 12.783.174 14 1.918 14h12.164c1.744 0 2.426-1.217 1.512-2.703zM8 12c-.552 0-1-.447-1-1s.448-1 1-1c.553 0 1 .447 1 1s-.447 1-1 1zm.697-3H7.3l-.4-5h2.2l-.403 5z"/></g></svg>';
			break;
		case 'website':
			$svg = '<svg class="genericon genericon-website" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M8 2C4.687 2 2 4.687 2 8s2.687 6 6 6 6-2.687 6-6-2.687-6-6-6zM3.72 5.527l.283.08-.236.022-.137.048-.035.008c.034-.064.067-.128.103-.19l.022.03zM8 13c-.155 0-.3-.032-.453-.046l.26-.207.015-.13-.134-.182.282.04.312-.71.392-.24.216-.533.178-.51-.01-.45-.245-.153-.375-.032-.37-.08.065-.13-.26.075.063-.38-.065-.044-.272-.152-.38-.263-.528-.17-.154-.053-.114.19.02-.21-.31.138-.467.108-.105.05.156.072.117-.085.065.037-.06.482-.11.414-.06.13.084.217.248.44.526.514.087.49.075 1.075.032.1C4.585 12.244 3 10.31 3 8c0-.498.095-.97.23-1.423l.21.362.002.28.04.18.078.096.04.13.063.08.005-.134-.058-.516.04.127.174.37.39.617.34.142.307.074.317-.204.116-.34-.447.24-.232-.253.05-.34.386-.31H5.71l.186.37.063-.2.2-.464.257-.21.076-.182.2-.158.273-.15.11-.13.245-.116.204-.044-.126.147.36-.146-.09-.056-.105-.12.04-.133-.333.092.428-.17.584-.148-.16-.157-.08-.43-.226.08-.07-.145-.26-.13-.257.176-.153.296-.263.27L6.6 5.1l-.3-.14-.107-.118.43-.33.283-.163.584-.192-.372.034-.086-.178-.22-.023-.044.142-.234.057-.372-.048-.272.06-.25-.063-.373-.097-.3.01C5.813 3.402 6.856 3 8 3c.563 0 1.096.114 1.602.287L9.37 3.3l-.54.132-.252.06.173.134.36.152.097.17-.132.255.05.466.467-.227.604-.268.468-.08.062-.07-.166-.02.036-.074.257.042-.16-.14.035-.013c.602.393 1.106.913 1.49 1.52l-.113.09-.316.173-.162.065.188.208-.067.17-.364-.02-.104.197-.02.317.183.072.396-.09.204-.275.186-.166.226-.02.105-.052.044.04c.12.284.212.583.278.89l-.19-.08-.202-.29-.52.057-.215.075-.295-.003-.288.273-.102.2-.146.162-.104.102-.178.274-.038.142-.044.06-.007.423.006.254.304.418.312.227.412-.024.436-.165.184.155.198.06.27.196-.116.397.05.083C11.853 11.733 10.07 13 8 13z"/></g></svg>';
			break;
		case 'week':
			$svg = '<svg class="genericon genericon-week" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M9 6.473v-.01l-.002-.016c-.026-.237-.215-.424-.452-.445h-.002c-.007 0-.014 0-.022-.002H6.5c-.276 0-.5.224-.5.5s.224.5.5.5h1.36l-.845 3.38c-.067.267.096.538.364.605.267.066.538-.097.605-.364l1-4c.01-.04.015-.08.015-.12v-.002-.014-.01zM11 3V2h-1v1H5V2H4v1H2v10h11V3h-2zm1 8c0 .553-.447 1-1 1H4c-.552 0-1-.447-1-1V6c0-.553.448-1 1-1h7c.553 0 1 .447 1 1v5z"/></g></svg>';
			break;
		case 'xpost':
			$svg = '<svg class="genericon genericon-xpost" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M13 4c0-1.104-.896-2-2-2s-2 .896-2 2c0 .738.404 1.376 1 1.723V7c0 1.104-.896 2-2 2-.732 0-1.41.21-2 .555V5.723C6.595 5.376 7 4.738 7 4c0-1.104-.896-2-2-2s-2 .896-2 2c0 .738.405 1.376 1 1.723V14h2v-1c0-1.104.896-2 2-2 2.21 0 4-1.79 4-4V5.723c.596-.347 1-.985 1-1.723zM5 3c.552 0 1 .448 1 1s-.448 1-1 1-1-.448-1-1 .448-1 1-1zm6 2c-.553 0-1-.448-1-1s.447-1 1-1 1 .448 1 1-.447 1-1 1z"/></g></svg>';
			break;
		case 'zoom':
			$svg = '<svg class="genericon genericon-zoom" height="16" width="16" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><g><path d="M7 4H6v2H4v1h2v2h1V7h2V6H7V4zm3.134 5.134c.54-.74.866-1.647.866-2.634C11 4.015 8.985 2 6.5 2S2 4.015 2 6.5 4.015 11 6.5 11c.987 0 1.893-.327 2.634-.866L13 14l1-1-3.866-3.866zM6.5 10C4.567 10 3 8.433 3 6.5S4.567 3 6.5 3C8.434 3 10 4.567 10 6.5S8.434 10 6.5 10z"/></g></svg>';
			break;
		default: 
			$svg = 'Need to specify a genericon';
			break;
	}

	return $svg;
}
