<?php

/**
 * Globally registers the 'genericons' plugin
 */

/* !!!


IF YOU ARE EDITING THIS FILE, THEN YOU ARE EDITING A FILE THAT GETS OUTPUT FROM THE GENERICONS REPO!

https://github.com/Automattic/Genericons

DO NOT EDIT THIS FILE! 

If you need to edit this file, edit index-header.php and index-footer.php in the Genericons repo instead
OR if you're looking to change how SVGs get output, you'll need to edit strings in the Gruntfile :)

!!! */


function get_genericon( $genericon ) {
	$svg = "";

	switch ( $genericon ) {
		case 'activity':
			$svg = '<svg class="genericon genericon-activity" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><style>.st0{fill:#231F20;}</style><path class="st0" d="M10 11.8L8.5 7.7l-1.6 3.7c-.3.8-1.4.8-1.8.1L3.9 9l-1.1 1.6-1.6-1.2 2-3c.4-.6 1.4-.6 1.7.1l1 2.1 1.7-4c.3-.8 1.5-.8 1.8 0l1.6 4 2.1-5.9 1.8.6-3 8.5c-.3.9-1.5.9-1.9 0z"/></g></svg>';
			break;
		case 'anchor':
			$svg = '<svg class="genericon genericon-anchor" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M12 8v2.5c0 .8-.7 1.5-1.5 1.5S9 11.3 9 10.5V9h1c.3 0 .5-.2.5-.5S10.3 8 10 8H9V5.8c.7-.3 1.1-1 1.1-1.8 0-1.1-.9-2-2-2s-2 .9-2 2c0 .7.4 1.3.9 1.7V8H6c-.3 0-.5.2-.5.5s.2.5.5.5h1v1.5c0 .8-.7 1.5-1.5 1.5S4 11.3 4 10.5V8c-1.1 0-2 .9-2 2v.5C2 12.4 3.6 14 5.5 14c1 0 1.9-.4 2.5-1.1.6.6 1.5 1.1 2.5 1.1 1.9 0 3.5-1.6 3.5-3.5V10c0-1.1-.9-2-2-2zM8 3.5c.3 0 .5.2.5.5s-.2.5-.5.5-.5-.2-.5-.5.2-.5.5-.5z"/></g></svg>';
			break;
		case 'aside':
			$svg = '<svg class="genericon genericon-aside" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M11 3H5c-1.1 0-2 .9-2 2v6c0 1.1.9 2 2 2h5l3-3V5c0-1.1-.9-2-2-2zm0 5h-1c-1.1 0-2 .9-2 2v1H5V5h6v3z"/></g></svg>';
			break;
		case 'attachment':
			$svg = '<svg class="genericon genericon-attachment" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M9.5 1C8.1 1 7 2.2 7 3.5v7c0 .8.7 1.5 1.5 1.5s1.5-.7 1.5-1.5V5H9v5.5c0 .3-.2.5-.5.5s-.5-.2-.5-.5v-7C8 2.7 8.7 2 9.5 2s1.5.7 1.5 1.5v8c0 1.4-1.1 2.5-2.5 2.5S6 12.9 6 11.5V5H5v6.5C5 13.4 6.6 15 8.5 15s3.5-1.6 3.5-3.5v-8C12 2.2 10.9 1 9.5 1z"/></g></svg>';
			break;
		case 'audio-mute':
			$svg = '<svg class="genericon genericon-audio-mute" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M7.3 2.7L4 6H2v4h2l3.3 3.3c.6.6 1.7.2 1.7-.7V3.4c0-.9-1.1-1.3-1.7-.7z"/></g></svg>';
			break;
		case 'audio':
			$svg = '<svg class="genericon genericon-audio" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M7.3 2.7L4 6H2v4h2l3.3 3.3c.6.6 1.7.2 1.7-.7V3.4c0-.9-1.1-1.3-1.7-.7zM13 3l-.7.7C13.3 4.8 14 6.3 14 8s-.7 3.2-1.8 4.2l.7.7c1.3-1.3 2.1-3 2.1-5 0-1.9-.8-3.6-2-4.9zm-1.5 1.5l-.7.7c.8.7 1.2 1.7 1.2 2.8s-.5 2.1-1.2 2.8l.7.7c.9-.9 1.5-2.1 1.5-3.5s-.6-2.6-1.5-3.5z"/></g></svg>';
			break;
		case 'bold':
			$svg = '<svg class="genericon genericon-bold" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M12 5c0-1.7-1.4-3-3-3H4v12h5c1.6 0 3-1.3 3-3v-1c0-.8-.3-1.5-.8-2 .5-.5.8-1.2.8-2V5zM6 4h3c.5 0 1 .5 1 1v1c0 .5-.5 1-1 1H6V4zm4 7c0 .5-.5 1-1 1H6V9h3c.5 0 1 .5 1 1v1z"/></g></svg>';
			break;
		case 'book':
			$svg = '<svg class="genericon genericon-book" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M11 2H7v7L6 8 5 9V2H3v12h8c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2z"/></g></svg>';
			break;
		case 'bug':
			$svg = '<svg class="genericon genericon-bug" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M8 2.5C6.6 2.5 5.5 3.6 5.5 5h5c0-1.4-1.1-2.5-2.5-2.5zm5 6h-1V7.4l.7-.7c.4-.4.4-1 0-1.4s-1-.4-1.4 0l-.7.7H5.4l-.7-.7c-.4-.4-1-.4-1.4 0s-.4 1 0 1.4l.7.7v1.1H3c-.6 0-1 .4-1 1s.4 1 1 1h1.1c0 .3.1.6.2.8l-1 1c-.4.4-.4 1 0 1.4s1 .4 1.4 0l.7-.7c.7.6 1.6 1 2.6 1s1.9-.4 2.6-1l.7.7c.2.2.5.3.7.3s.5-.1.7-.3c.4-.4.4-1 0-1.4l-1-1c.1-.3.2-.5.2-.8H13c.6 0 1-.4 1-1s-.4-1-1-1z"/></g></svg>';
			break;
		case 'cart':
			$svg = '<svg class="genericon genericon-cart" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M11 12c-.6 0-1 .4-1 1s.4 1 1 1 1-.4 1-1-.4-1-1-1zm-6 0c-.6 0-1 .4-1 1s.4 1 1 1 1-.4 1-1-.4-1-1-1zm6-2H5V9h5.6c.8 0 1.5-.5 1.9-1.3L14 4H5V3c0-.6-.4-1-1-1H2v1h2v7c0 .6.4 1 1 1h7c0-.6-.4-1-1-1z"/></g></svg>';
			break;
		case 'category':
			$svg = '<svg class="genericon genericon-category" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M13 5H8l-.7-1.4c-.2-.4-.5-.6-.9-.6H3c-.5 0-1 .5-1 1v8c0 .6.5 1 1 1h10c.6 0 1-.4 1-1V6c0-.6-.4-1-1-1z"/></g></svg>';
			break;
		case 'chat':
			$svg = '<svg class="genericon genericon-chat" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M7 3H3c-1.1 0-2 .9-2 2v7l2.4-2.4c.4-.4.9-.6 1.4-.6H6V8c0-1.7 1.3-3 3-3 0-1.1-.9-2-2-2zm6 3H9c-1.1 0-2 .9-2 2v2c0 1.1.9 2 2 2h2.2c.5 0 1 .2 1.4.6L15 15V8c0-1.1-.9-2-2-2z"/></g></svg>';
			break;
		case 'checkmark':
			$svg = '<svg class="genericon genericon-checkmark" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M13.3 3.3l-6.8 6.8-2.8-2.8-1.4 1.4 4.2 4.2 8.2-8.2"/></g></svg>';
			break;
		case 'close-alt':
			$svg = '<svg class="genericon genericon-close-alt" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M14.7 2.7l-1.4-1.4L8 6.6 2.7 1.3 1.3 2.7 6.6 8l-5.3 5.3 1.4 1.4L8 9.4l5.3 5.3 1.4-1.4L9.4 8"/></g></svg>';
			break;
		case 'close':
			$svg = '<svg class="genericon genericon-close" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M12.7 4.7l-1.4-1.4L8 6.6 4.7 3.3 3.3 4.7 6.6 8l-3.3 3.3 1.4 1.4L8 9.4l3.3 3.3 1.4-1.4L9.4 8"/></g></svg>';
			break;
		case 'cloud-download':
			$svg = '<svg class="genericon genericon-cloud-download" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M9 11H7v2H5l3 3 3-3H9v-2zm4-3h-.2c.1-.3.2-.6.2-1 0-1.7-1.3-3-3-3-1.2 0-2.2.7-2.7 1.7-.5-.4-1.1-.7-1.8-.7C4.1 5 3 6.1 3 7.5V8c-1.1 0-2 .9-2 2s.9 2 2 2h3v-2h4v2h3c1.1 0 2-.9 2-2s-.9-2-2-2z"/></g></svg>';
			break;
		case 'cloud-upload':
			$svg = '<svg class="genericon genericon-cloud-upload" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M13 8h-.2c.1-.3.2-.6.2-1 0-1.7-1.3-3-3-3-1.2 0-2.2.7-2.7 1.7-.5-.4-1.1-.7-1.8-.7C4.1 5 3 6.1 3 7.5V8c-1.1 0-2 .9-2 2s.9 2 2 2h4v-2H5l3-3 3 3H9v2h4c1.1 0 2-.9 2-2s-.9-2-2-2z"/></g></svg>';
			break;
		case 'cloud':
			$svg = '<svg class="genericon genericon-cloud" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M13 8h-.2c.1-.3.2-.6.2-1 0-1.7-1.3-3-3-3-1.2 0-2.2.7-2.7 1.7-.5-.4-1.1-.7-1.8-.7C4.1 5 3 6.1 3 7.5c0 .2 0 .3.1.5H3c-1.1 0-2 .9-2 2s.9 2 2 2h10c1.1 0 2-.9 2-2s-.9-2-2-2z"/></g></svg>';
			break;
		case 'code':
			$svg = '<svg class="genericon genericon-code" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M5.3 12.7L.6 8l4.7-4.7 1.4 1.4L3.4 8l3.3 3.3M10.7 12.7l-1.4-1.4L12.6 8 9.3 4.7l1.4-1.4L15.4 8"/></g></svg>';
			break;
		case 'cog':
			$svg = '<svg class="genericon genericon-cog" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M13 8c0-.4-.1-.8-.1-1.1l1.1-.8c.4-.3.5-.9.3-1.3l-.3-.6c-.3-.5-.8-.6-1.3-.4l-1.2.5c-.5-.5-1.2-.9-1.9-1.1l-.3-1.4c0-.5-.5-.8-.9-.8h-.7c-.5 0-.9.4-1 .9l-.2 1.3c-.7.3-1.3.6-1.9 1.1l-1.2-.5c-.5-.2-1 0-1.3.4l-.3.6c-.3.5-.2 1 .2 1.3l1.1.8c0 .3-.1.7-.1 1.1 0 .4.1.8.1 1.1L2 9.9c-.4.3-.5.9-.3 1.3l.3.6c.3.5.8.6 1.3.4l1.2-.5c.5.5 1.2.9 1.9 1.1l.3 1.4c.1.5.5.8 1 .8h.7c.5 0 1-.4 1-.9l.1-1.3c.7-.2 1.4-.6 1.9-1.1l1.2.5c.5.2 1 0 1.3-.4l.3-.6c.2-.4.1-1-.3-1.3l-1.1-.8c.1-.3.2-.7.2-1.1zm-5 2.5c-1.4 0-2.5-1.1-2.5-2.5S6.6 5.5 8 5.5s2.5 1.1 2.5 2.5-1.1 2.5-2.5 2.5z"/></g></svg>';
			break;
		case 'collapse':
			$svg = '<svg class="genericon genericon-collapse" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M8 4.6l-6.7 6.7 1.4 1.4L8 7.4l5.3 5.3 1.4-1.4"/></g></svg>';
			break;
		case 'comment':
			$svg = '<svg class="genericon genericon-comment" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M12 4H4c-1.1 0-2 .9-2 2v8l2.4-2.4c.4-.4.9-.6 1.4-.6H12c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2z"/></g></svg>';
			break;
		case 'day':
			$svg = '<svg class="genericon genericon-day" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M12 3h-1V2H9v1H7V2H5v1H4c-1.1 0-2 .9-2 2v6c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm-3 8H8V6.2l-.8.3-.4-1L9 4.8V11z"/></g></svg>';
			break;
		case 'document':
			$svg = '<svg class="genericon genericon-document" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M10 1H5c-1.1 0-2 .9-2 2v9c0 1.1.9 2 2 2h6c1.1 0 2-.9 2-2V4l-3-3zM5 12V3h3v1c0 1.1.9 2 2 2h1v6H5z"/></g></svg>';
			break;
		case 'download':
			$svg = '<svg class="genericon genericon-download" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M11 7H9V3H7v4H5l3 3 3-3zm-8 4v2h10v-2H3z"/></g></svg>';
			break;
		case 'edit':
			$svg = '<svg class="genericon genericon-edit" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M12.6 6.9l.5-.5c.8-.8.8-2 0-2.8l-.7-.7c-.8-.8-2-.8-2.8 0l-.5.5 3.5 3.5zM8.4 4.1L2 10.5V14h3.5l6.4-6.4"/></g></svg>';
			break;
		case 'ellipsis':
			$svg = '<svg class="genericon genericon-ellipsis" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M3 6.2C2 6.2 1.2 7 1.2 8S2 9.8 3 9.8 4.8 9 4.8 8 4 6.2 3 6.2zm10 0c-1 0-1.8.8-1.8 1.8S12 9.8 13 9.8 14.8 9 14.8 8 14 6.2 13 6.2zm-5 0C7 6.2 6.2 7 6.2 8S7 9.8 8 9.8 9.8 9 9.8 8 9 6.2 8 6.2z"/></g></svg>';
			break;
		case 'expand':
			$svg = '<svg class="genericon genericon-expand" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M8 12.7L1.3 6l1.4-1.4L8 9.9l5.3-5.3L14.7 6"/></g></svg>';
			break;
		case 'external':
			$svg = '<svg class="genericon genericon-external" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M11 11H5V5h1V3H5c-1.1 0-2 .9-2 2v6c0 1.1.9 2 2 2h6c1.1 0 2-.9 2-2v-1h-2v1zM8 3v2h1.6L6.3 8.3l1.4 1.4L11 6.4V8h2V3H8z"/></g></svg>';
			break;
		case 'fastforward':
			$svg = '<svg class="genericon genericon-fastforward" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M14.9 7.1L9.5 3.9C8.8 3.5 8 4 8 4.8v2.5l-.1-.1-5.4-3.3C1.8 3.5 1 4 1 4.8v6.5c0 .8.8 1.3 1.5.9L7.9 9S8 9 8 8.9v2.5c0 .8.8 1.3 1.5.9l5.4-3.2c.7-.6.7-1.6 0-2z"/></g></svg>';
			break;
		case 'feed':
			$svg = '<svg class="genericon genericon-feed" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M2 6v2c3.3 0 6 2.7 6 6h2c0-4.4-3.6-8-8-8zm0-4v2c5.5 0 10 4.5 10 10h2C14 7.4 8.6 2 2 2zm1.5 9c-.8 0-1.5.7-1.5 1.5S2.7 14 3.5 14 5 13.3 5 12.5 4.3 11 3.5 11z"/></g></svg>';
			break;
		case 'flag':
			$svg = '<svg class="genericon genericon-flag" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M9.4 4.4l-.8-.8c-.4-.4-.9-.6-1.4-.6H3v11h2v-4h2.2c.5 0 1 .2 1.4.6l.8.8c.4.4.9.6 1.4.6H13V5h-2.2c-.5 0-1-.2-1.4-.6z"/></g></svg>';
			break;
		case 'fullscreen':
			$svg = '<svg class="genericon genericon-fullscreen" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M10 2v2h3v3h2V2h-5zM1 7h2V4h3V2H1v5zm12 5h-3v2h5V9h-2v3zM3 9H1v5h5v-2H3V9z"/></g></svg>';
			break;
		case 'gallery':
			$svg = '<svg class="genericon genericon-gallery" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M12 10V4c0-1.1-.9-2-2-2H4c-1.1 0-2 .9-2 2v6c0 1.1.9 2 2 2h6c1.1 0 2-.9 2-2zM5.5 7l1.1 1.6 1.5-2.4L10 10H4l1.5-3zM13 5v8H5c0 1.1.9 2 2 2h6c1.1 0 2-.9 2-2V7c0-1.1-.9-2-2-2z"/></g></svg>';
			break;
		case 'heart':
			$svg = '<svg class="genericon genericon-heart" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M8 13L2.9 8.2c-1.1-1.1-1.2-3-.2-4.2 1-1.2 2.8-1.3 4-.2L8 5l1.3-1.2c1.2-1.1 3-1 4 .2 1.1 1.2 1 3.1-.2 4.2L8 13z"/></g></svg>';
			break;
		case 'help':
			$svg = '<svg class="genericon genericon-help" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M8 2C4.7 2 2 4.7 2 8s2.7 6 6 6 6-2.7 6-6-2.7-6-6-6zm0 10c-.6 0-1-.4-1-1s.4-1 1-1 1 .4 1 1-.4 1-1 1zm1.5-3.5c-.7.2-.7.6-.7.7H7.2c0-1 .6-1.8 1.8-2.2.7-.2.7-.7.7-.8 0-.4-.3-.8-.8-.8H7c-.4 0-.8.3-.8.8H4.8C4.8 5 5.8 4 7 4h2c1.2 0 2.2 1 2.2 2.2 0 1.1-.6 1.9-1.7 2.3z"/></g></svg>';
			break;
		case 'hide':
			$svg = '<svg class="genericon genericon-hide" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M14.8 7.6c-.4-.6-.8-1.2-1.3-1.7L12.4 7c.3.3.6.6.8 1-1 1.5-2.7 2.5-4.5 2.7l-1.5 1.5c.3 0 .6.1.8.1 2.8 0 5.4-1.5 6.8-3.9L15 8l-.2-.4zm-2.5-5.3l-1.8 1.8c-.8-.2-1.6-.4-2.5-.4-2.8 0-5.4 1.5-6.8 3.9L1 8l.2.4c.6 1 1.4 1.9 2.4 2.6l-1.3 1.3 1.4 1.4 10-10-1.4-1.4zM5.5 7.5c0 .5.1.9.3 1.2l-1 1.1c-.8-.4-1.5-1-2-1.8.9-1.4 2.3-2.3 3.9-2.6-.7.4-1.2 1.2-1.2 2.1z"/></g></svg>';
			break;
		case 'hierarchy':
			$svg = '<svg class="genericon genericon-hierarchy" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M2 5h2V3H2v2zm4-2v2h8V3H6zM2 9h2V7H2v2zm9-2H6v2h5V7zm-9 6h2v-2H2v2zm4 0h7v-2H6v2z"/></g></svg>';
			break;
		case 'home':
			$svg = '<svg class="genericon genericon-home" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M7.4 3.5l-4 3.2c-.3.2-.4.5-.4.8V13h3.5v-2.5C6.5 9.7 7.2 9 8 9s1.5.7 1.5 1.5V13H13V7.5c0-.3-.1-.6-.4-.8l-4-3.2c-.3-.3-.9-.3-1.2 0z"/></g></svg>';
			break;
		case 'image':
			$svg = '<svg class="genericon genericon-image" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M13 5h-2l-1-2H6L5 5H3c-.6 0-1 .4-1 1v6c0 .5.4 1 1 1h10c.5 0 1-.4 1-1V6c0-.6-.4-1-1-1zm-5 7c-1.7 0-3-1.3-3-3s1.3-3 3-3 3 1.3 3 3-1.3 3-3 3zm0-5c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2z"/></g></svg>';
			break;
		case 'info':
			$svg = '<svg class="genericon genericon-info" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M8 2C4.7 2 2 4.7 2 8s2.7 6 6 6 6-2.7 6-6-2.7-6-6-6zm0 2c.6 0 1 .4 1 1s-.4 1-1 1-1-.4-1-1 .4-1 1-1zm2 8H6v-1h1.2V8h-1V7h2.5v4H10v1z"/></g></svg>';
			break;
		case 'italic':
			$svg = '<svg class="genericon genericon-italic" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M11.7 4l.4-2h-6l-.4 2h2l-1.4 8h-2l-.4 2h6l.4-2h-2l1.4-8"/></g></svg>';
			break;
		case 'key':
			$svg = '<svg class="genericon genericon-key" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M15 7H8.9c-.5-1.7-2-3-3.9-3-2.2 0-4 1.8-4 4s1.8 4 4 4c1.9 0 3.4-1.3 3.9-3H12v2h2V9h1V7zM5 10c-1.1 0-2-.9-2-2s.9-2 2-2 2 .9 2 2-.9 2-2 2z"/></g></svg>';
			break;
		case 'link':
			$svg = '<svg class="genericon genericon-link" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M13 4h-3c-1.1 0-2 .9-2 2v.8H7V6c0-1.1-.9-2-2-2H2C.9 4 0 4.9 0 6v3c0 1.1.9 2 2 2h3c1.1 0 2-.9 2-2v-.8h1V9c0 1.1.9 2 2 2h3c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2zM5.5 9c0 .3-.2.5-.5.5H2c-.3 0-.5-.2-.5-.5V6c0-.3.2-.5.5-.5h3c.3 0 .5.2.5.5v.8H5c-.4 0-.8.3-.8.8s.4.6.8.6h.5V9zm8 0c0 .3-.2.5-.5.5h-3c-.3 0-.5-.2-.5-.5v-.8h.5c.4 0 .8-.3.8-.8s-.4-.6-.8-.6h-.5V6c0-.3.2-.5.5-.5h3c.3 0 .5.2.5.5v3z"/></g></svg>';
			break;
		case 'location':
			$svg = '<svg class="genericon genericon-location" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M11.5 3.5c-2-2-5.1-2-7.1 0s-2 5.1 0 7.1L8 14.1l3.5-3.5c2-2 2-5.2 0-7.1zM9.4 8.4c-.8.8-2 .8-2.8 0-.8-.8-.8-2 0-2.8.8-.8 2-.8 2.8 0 .8.8.8 2 0 2.8z"/></g></svg>';
			break;
		case 'lock':
			$svg = '<svg class="genericon genericon-lock" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M12 8V6c0-2.2-1.8-4-4-4S4 3.8 4 6v2c-.6 0-1 .4-1 1v4c0 .6.4 1 1 1h8c.6 0 1-.4 1-1V9c0-.6-.4-1-1-1zM6 8V6c0-1.1.9-2 2-2s2 .9 2 2v2H6z"/></g></svg>';
			break;
		case 'mail':
			$svg = '<svg class="genericon genericon-mail" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M12 3H4c-1.1 0-2 .9-2 2v5c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm1 3.2L8 9.1 3 6.2V5l5 2.9L13 5v1.2z"/></g></svg>';
			break;
		case 'menu':
			$svg = '<svg class="genericon genericon-menu" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M0 14h16v-2H0v2zM0 2v2h16V2H0zm0 7h16V7H0v2z"/></g></svg>';
			break;
		case 'microphone':
			$svg = '<svg class="genericon genericon-microphone" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M8 10c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2s-2 .9-2 2v4c0 1.1.9 2 2 2zm3-2c0 1.7-1.3 3-3 3S5 9.7 5 8H3c0 2.4 1.7 4.4 4 4.9V15h2v-2.1c2.3-.5 4-2.5 4-4.9h-2z"/></g></svg>';
			break;
		case 'minus':
			$svg = '<svg class="genericon genericon-minus" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M3 7h10v2H3z"/></g></svg>';
			break;
		case 'month':
			$svg = '<svg class="genericon genericon-month" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M12 3h-1V2H9v1H7V2H5v1H4c-1.1 0-2 .9-2 2v6c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM9 7c0 .4-.2.7-.4 1 .2.3.4.6.4 1v.5c0 .8-.7 1.5-1.5 1.5h-1C5.7 11 5 10.3 5 9.5V9h1v.5c0 .3.2.5.5.5h1c.3 0 .5-.2.5-.5V9c0-.3-.2-.5-.5-.5H7v-1h.5c.3 0 .5-.2.5-.5v-.5c0-.3-.2-.5-.5-.5h-1c-.3 0-.5.2-.5.5V7H5v-.5C5 5.7 5.7 5 6.5 5h1C8.3 5 9 5.7 9 6.5V7zm2 4h-1V5h1v6z"/></g></svg>';
			break;
		case 'move':
			$svg = '<svg class="genericon genericon-move" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M12.5 5.5V7H9V3.5h1.5L8 1 5.5 3.5H7V7H3.5V5.5L1 8l2.5 2.5V9H7v3.5H5.5L8 15l2.5-2.5H9V9h3.5v1.5L15 8"/></g></svg>';
			break;
		case 'next':
			$svg = '<svg class="genericon genericon-next" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M3 7h6.6L7.3 4.7l1.4-1.4L13.4 8l-4.7 4.7-1.4-1.4L9.6 9H3"/></g></svg>';
			break;
		case 'notice':
			$svg = '<svg class="genericon genericon-notice" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M8 2C4.7 2 2 4.7 2 8s2.7 6 6 6 6-2.7 6-6-2.7-6-6-6zm0 10c-.6 0-1-.4-1-1s.4-1 1-1 1 .4 1 1-.4 1-1 1zm.8-3H7.2L7 4h2l-.2 5z"/></g></svg>';
			break;
		case 'paintbrush':
			$svg = '<svg class="genericon genericon-paintbrush" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M14.1 1.9c-.6-.6-1.5-.6-2.1 0l-6 6L8.1 10l6-6c.5-.5.5-1.5 0-2.1zM6.5 9.7c-.8-.9-1.9-1.1-2.7-.6-.8.4-1.2 1.3-1.2 2.2-.1.9-.7 1.6-1.6 2 .5.7 2.2 1.2 4.2.5s2.3-2.9 1.3-4.1z"/></g></svg>';
			break;
		case 'pause':
			$svg = '<svg class="genericon genericon-pause" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M4 13h3V3H4v10zM9 3v10h3V3H9z"/></g></svg>';
			break;
		case 'phone':
			$svg = '<svg class="genericon genericon-phone" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M10 1H6c-1.1 0-2 .9-2 2v10c0 1.1.9 2 2 2h4c1.1 0 2-.9 2-2V3c0-1.1-.9-2-2-2zM8.5 14h-1c-.3 0-.5-.2-.5-.5s.2-.5.5-.5h1c.3 0 .5.2.5.5s-.2.5-.5.5zm2.5-2H5V3h6v9z"/></g></svg>';
			break;
		case 'picture':
			$svg = '<svg class="genericon genericon-picture" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M12 2H4c-1.1 0-2 .9-2 2v8c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zm-8 9l2-4 1.5 3 2-4 2.5 5H4z"/></g></svg>';
			break;
		case 'pinned':
			$svg = '<svg class="genericon genericon-pinned" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M12 8c0-.5-.5-1-1-1h-.6l-.3-3c.5-.1.9-.5.9-1s-.5-1-1-1H6c-.5 0-1 .5-1 1s.4.9.9 1l-.3 3H5c-.5 0-1 .5-1 1v1h3v6l2-1V9h3V8z"/></g></svg>';
			break;
		case 'play':
			$svg = '<svg class="genericon genericon-play" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M3 12.2V3.8c0-.8.8-1.3 1.5-.9l7.1 4.2c.6.4.6 1.3 0 1.7L4.5 13c-.7.5-1.5 0-1.5-.8z"/></g></svg>';
			break;
		case 'plugin':
			$svg = '<svg class="genericon genericon-plugin" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M11 6.5V3c0-.6-.4-1-1-1s-1 .4-1 1v3.5H7V3c0-.6-.4-1-1-1s-1 .4-1 1v3.5H3V10c0 1.1.9 2 2 2h2v3l2-.5V12h2c1.1 0 2-.9 2-2V6.5h-2z"/></g></svg>';
			break;
		case 'plus':
			$svg = '<svg class="genericon genericon-plus" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M13 7H9V3H7v4H3v2h4v4h2V9h4"/></g></svg>';
			break;
		case 'previous':
			$svg = '<svg class="genericon genericon-previous" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M13 7H6.4l2.3-2.3-1.4-1.4L2.6 8l4.7 4.7 1.4-1.4L6.4 9H13"/></g></svg>';
			break;
		case 'print':
			$svg = '<svg class="genericon genericon-print" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M5 3h6v2.5H5zM11 6H5c-1.1 0-2 .9-2 2v3h2v3h6v-3h2V8c0-1.1-.9-2-2-2zm-1 7H6v-3h4v3zm1-4.2c-.4 0-.8-.3-.8-.8s.3-.8.8-.8.8.3.8.8-.4.8-.8.8z"/></g></svg>';
			break;
		case 'quote':
			$svg = '<svg class="genericon genericon-quote" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M2 9h3c0 1.1-.9 2-2 2v2c2.2 0 4-1.8 4-4V4H2v5zm7-5v5h3c0 1.1-.9 2-2 2v2c2.2 0 4-1.8 4-4V4H9z"/></g></svg>';
			break;
		case 'refresh':
			$svg = '<svg class="genericon genericon-refresh" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M3.8 3.8C2.7 4.9 2 6.3 2 8c0 3 2.2 5.4 5 5.9v-2.1c-1.7-.4-3-2-3-3.9 0-1.1.5-2.1 1.2-2.8L7 7V2H2l1.8 1.8zM14 8c0-3-2.2-5.4-5-5.9v2.1c1.7.4 3 2 3 3.9 0 1.1-.5 2.1-1.2 2.8L9.1 9.1 9 9v5h5l-1.8-1.8C13.3 11.1 14 9.7 14 8z"/></g></svg>';
			break;
		case 'reply':
			$svg = '<svg class="genericon genericon-reply" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M10 6H8V3L3 8l5 5v-3h2c1 0 2 .4 2.8 1.2l1.2 1.2V10c0-2.2-1.8-4-4-4z"/></g></svg>';
			break;
		case 'rewind':
			$svg = '<svg class="genericon genericon-rewind" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M1.1 7.1l5.4-3.2c.7-.4 1.5.1 1.5.9v2.5l.1-.1L13.5 4c.7-.5 1.5 0 1.5.8v6.5c0 .8-.8 1.3-1.5.9L8.1 8.9s-.1 0-.1-.1v2.5c0 .8-.8 1.3-1.5.9L1.1 8.9c-.7-.4-.7-1.4 0-1.8z"/></g></svg>';
			break;
		case 'search':
			$svg = '<svg class="genericon genericon-search" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M14.7 13.3L11 9.6c.6-.9 1-2 1-3.1C12 3.5 9.5 1 6.5 1S1 3.5 1 6.5 3.5 12 6.5 12c1.2 0 2.2-.4 3.1-1l3.7 3.7 1.4-1.4zM2.5 6.5c0-2.2 1.8-4 4-4s4 1.8 4 4-1.8 4-4 4-4-1.8-4-4z"/></g></svg>';
			break;
		case 'send-to-phone':
			$svg = '<svg class="genericon genericon-send-to-phone" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M6 10l3-3-3-3v2H2v2h4v2zm4-9H6c-1.1 0-2 .9-2 2v2h1V3h6v9H5V9H4v4c0 1.1.9 2 2 2h4c1.1 0 2-.9 2-2V3c0-1.1-.9-2-2-2zM8.5 14h-1c-.3 0-.5-.2-.5-.5s.2-.5.5-.5h1c.3 0 .5.2.5.5s-.2.5-.5.5z"/></g></svg>';
			break;
		case 'send-to-tablet':
			$svg = '<svg class="genericon genericon-send-to-tablet" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M4 10l3-3-3-3v2H0v2h4v2z"/><path d="M12 0H4C2.9 0 2 .9 2 2v3h1V2h10v11H3V9H2v5c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V2c0-1.1-.9-2-2-2zM8.5 15h-1c-.3 0-.5-.2-.5-.5s.2-.5.5-.5h1c.3 0 .5.2.5.5s-.2.5-.5.5z"/></g></svg>';
			break;
		case 'share':
			$svg = '<svg class="genericon genericon-share" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M12 6h-2v2h2v4H4V8h2V6H4c-1.1 0-2 .9-2 2v4c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V8c0-1.1-.9-2-2-2zM7 4.4V10h2V4.4l1.1 1.1 1.4-1.4L8 .6 4.5 4.1l1.4 1.4L7 4.4z"/></g></svg>';
			break;
		case 'show':
			$svg = '<svg class="genericon genericon-show" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M14.8 7.6c-1.4-2.4-4-3.9-6.8-3.9S2.6 5.2 1.2 7.6L1 8l.2.4c1.4 2.4 4 3.9 6.8 3.9s5.4-1.5 6.8-3.9L15 8l-.2-.4zM8 10.8c-2.1 0-4-1.1-5.2-2.8.9-1.4 2.3-2.3 3.9-2.6-.7.4-1.2 1.2-1.2 2.1C5.5 8.9 6.6 10 8 10s2.5-1.1 2.5-2.5c0-.9-.5-1.7-1.2-2.1 1.6.3 3 1.3 3.9 2.6-1.2 1.7-3.1 2.8-5.2 2.8z"/></g></svg>';
			break;
		case 'shuffle':
			$svg = '<svg class="genericon genericon-shuffle" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M12 10h-.9c-.3 0-.6-.2-.8-.4L7.4 5.3C6.9 4.5 5.9 4 4.9 4H2v2h2.9c.3 0 .6.2.8.4l2.8 4.2c.6.8 1.5 1.3 2.5 1.3h1v1.5l2.5-2.5L12 8.5V10zm-1.8-3.6c.2-.2.5-.4.9-.4h.9v1.5L14.5 5 12 2.5V4h-.9c-1 0-1.9.5-2.5 1.3l1.2 1.8.4-.7zM5.8 9.6c-.2.2-.5.4-.9.4H2v2h2.9c1 0 1.9-.5 2.5-1.3L6.2 8.9l-.4.7z"/></g></svg>';
			break;
		case 'sitemap':
			$svg = '<svg class="genericon genericon-sitemap" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M14 11.3V10c0-1.7-1.3-3-3-3H9V4.7c.6-.3 1-1 1-1.7 0-1.1-.9-2-2-2s-2 .9-2 2c0 .7.4 1.4 1 1.7V7H5c-1.7 0-3 1.3-3 3v1.3c-.6.3-1 1-1 1.7 0 1.1.9 2 2 2s2-.9 2-2c0-.7-.4-1.4-1-1.7V10c0-.6.4-1 1-1h2v2.3c-.6.3-1 1-1 1.7 0 1.1.9 2 2 2s2-.9 2-2c0-.7-.4-1.4-1-1.7V9h2c.6 0 1 .4 1 1v1.3c-.6.3-1 1-1 1.7 0 1.1.9 2 2 2s2-.9 2-2c0-.7-.4-1.4-1-1.7zM8 2.2c.4 0 .8.3.8.8s-.4.8-.8.8-.8-.4-.8-.8.4-.8.8-.8zM3 13.8c-.4 0-.8-.3-.8-.8s.3-.8.8-.8.8.3.8.8-.4.8-.8.8zm5 0c-.4 0-.8-.3-.8-.8s.3-.8.8-.8c.4 0 .8.3.8.8s-.4.8-.8.8zm5 0c-.4 0-.8-.3-.8-.8s.3-.8.8-.8.8.3.8.8-.4.8-.8.8z"/></g></svg>';
			break;
		case 'skip-ahead':
			$svg = '<svg class="genericon genericon-skip-ahead" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M4.5 2.9L10 6.2V3h3v10h-3V9.7L4.5 13c-.7.5-1.5 0-1.5-.8V3.8c0-.8.8-1.3 1.5-.9z"/></g></svg>';
			break;
		case 'skip-back':
			$svg = '<svg class="genericon genericon-skip-back" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M11.5 2.9L6 6.2V3H3v10h3V9.7l5.5 3.3c.7.5 1.5 0 1.5-.8V3.8c0-.8-.8-1.3-1.5-.9z"/></g></svg>';
			break;
		case 'spam':
			$svg = '<svg class="genericon genericon-spam" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M11 2H5L2 5v6l3 3h6l3-3V5l-3-3zM8 12c-.6 0-1-.4-1-1s.4-1 1-1 1 .4 1 1-.4 1-1 1zm.8-3H7.2L7 4h2l-.2 5z"/></g></svg>';
			break;
		case 'standard':
			$svg = '<svg class="genericon genericon-standard" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M11 2H5c-1.1 0-2 .9-2 2v8c0 1.1.9 2 2 2h5l3-3V4c0-1.1-.9-2-2-2zm0 7h-1c-1.1 0-2 .9-2 2v1H5V4h6v5z"/><path d="M6 5h4v1H6zM6 7h2v1H6z"/></g></svg>';
			break;
		case 'star-empty':
			$svg = '<svg class="genericon genericon-star-empty" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M8 5l.7 1.5.3.8.9.1 1.6.2-1.2 1.1-.7.5.2.8.3 1.6-1.4-.8-.7-.4-.7.4-1.4.8.3-1.6.2-.8-.7-.5-1.2-1.1 1.6-.2.9-.1.4-.8L8 5m0-3.7L6 5.9l-5 .5 3.7 3.3-1 4.9L8 12.2l4.3 2.5-1-4.9L15 6.4l-5-.5-2-4.6z"/></g></svg>';
			break;
		case 'star-half':
			$svg = '<svg class="genericon genericon-star-half" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M15 6.4l-5-.5-2-4.6-2 4.6-5 .5 3.7 3.3-1 4.9L8 12.2l4.3 2.5-1-4.9L15 6.4zm-5.2 3.7l.3 1.6-1.4-.8-.7-.5V5l.7 1.5.3.8.9.1 1.6.2-1.2 1.1-.7.5.2.9z"/></g></svg>';
			break;
		case 'star':
			$svg = '<svg class="genericon genericon-star" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M8 1.3l2 4.6 5 .5-3.7 3.4 1 4.9L8 12.2l-4.3 2.5 1-4.9L1 6.4l5-.5"/></g></svg>';
			break;
		case 'status':
			$svg = '<svg class="genericon genericon-status" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M11 5c0-1.7-1.3-3-3-3S5 3.3 5 5c0 1.3.8 2.4 2 2.8V14l2-1V7.8c1.2-.4 2-1.5 2-2.8z"/></g></svg>';
			break;
		case 'stop':
			$svg = '<svg class="genericon genericon-stop" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M4 4h8v8H4z"/></g></svg>';
			break;
		case 'subscribe':
			$svg = '<svg class="genericon genericon-subscribe" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M15 9h-5c-.6 0-1 .4-1 1v5c0 .6.4 1 1 1h5c.6 0 1-.4 1-1v-5c0-.6-.4-1-1-1zm0 4h-2v2h-1v-2h-2v-1h2v-2h1v2h2v1zm-3-5V5c0-1.1-.9-2-2-2H2C.9 3 0 3.9 0 5v5c0 1.1.9 2 2 2h6v-2c0-1.2.8-2 2-2h2zM6 9.1L1 6.2V5l5 2.9L11 5v1.2L6 9.1z"/></g></svg>';
			break;
		case 'subscribed':
			$svg = '<svg class="genericon genericon-subscribed" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M12 8V5c0-1.1-.9-2-2-2H2C.9 3 0 3.9 0 5v5c0 1.1.9 2 2 2h6v-2c0-1.2.8-2 2-2h2zM6 9.1L1 6.2V5l5 2.9L11 5v1.2L6 9.1zm9-.1h-5c-.6 0-1 .4-1 1v5c0 .6.4 1 1 1h5c.6 0 1-.4 1-1v-5c0-.6-.4-1-1-1zm-3 6l-2.1-2.1.7-.7 1.4 1.4 2.8-2.8.7.7L12 15z"/></g></svg>';
			break;
		case 'summary':
			$svg = '<svg class="genericon genericon-summary" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M12 3h-2c0-1.1-.9-2-2-2s-2 .9-2 2H4c-.6 0-1 .4-1 1v8c0 .5.4 1 1 1h8c.5 0 1-.4 1-1V4c0-.6-.4-1-1-1zm-4-.8c.4 0 .8.3.8.8s-.4.8-.8.8-.8-.4-.8-.8.4-.8.8-.8zM9 10H5V9h4v1zm2-2H5V7h6v1zm0-2H5V5h6v1z"/></g></svg>';
			break;
		case 'tablet':
			$svg = '<svg class="genericon genericon-tablet" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M12 0H4C2.9 0 2 .9 2 2v12c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V2c0-1.1-.9-2-2-2zM8.5 15h-1c-.3 0-.5-.2-.5-.5s.2-.5.5-.5h1c.3 0 .5.2.5.5s-.2.5-.5.5zm4.5-2H3V2h10v11z"/></g></svg>';
			break;
		case 'tag':
			$svg = '<svg class="genericon genericon-tag" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M11.3 4.3c-.2-.2-.4-.3-.7-.3H3c-.5 0-1 .5-1 1v6c0 .6.5 1 1 1h7.6c.3 0 .5-.1.7-.3L15 8l-3.7-3.7zM10 9c-.5 0-1-.5-1-1s.5-1 1-1 1 .5 1 1-.5 1-1 1z"/></g></svg>';
			break;
		case 'time':
			$svg = '<svg class="genericon genericon-time" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M8 2C4.7 2 2 4.7 2 8s2.7 6 6 6 6-2.7 6-6-2.7-6-6-6zm2.5 9.5L7.2 8.3V4h1.5v3.7l2.8 2.8-1 1z"/></g></svg>';
			break;
		case 'top':
			$svg = '<svg class="genericon genericon-top" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M3 12h10L8 7l-5 5zm0-8v2h10V4H3z"/></g></svg>';
			break;
		case 'trash':
			$svg = '<svg class="genericon genericon-trash" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M5.9 13h4.3c.5 0 .9-.4 1-.9l.8-6.6H4l.9 6.6c.1.5.5.9 1 .9zM11 3c0-.6-.4-1-1-1H6c-.6 0-1 .4-1 1L3 4v1h10V4l-2-1zM9.5 4h-3c-.3 0-.5-.2-.5-.5s.2-.5.5-.5h3c.3 0 .5.2.5.5s-.2.5-.5.5z"/></g></svg>';
			break;
		case 'unapprove':
			$svg = '<svg class="genericon genericon-unapprove" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M8 2C4.7 2 2 4.7 2 8s2.7 6 6 6 6-2.7 6-6-2.7-6-6-6zm4 6c0 .7-.2 1.4-.6 2L6 4.6c.6-.4 1.3-.6 2-.6 2.2 0 4 1.8 4 4zM4 8c0-.7.2-1.4.6-2l5.5 5.5c-.7.3-1.4.5-2.1.5-2.2 0-4-1.8-4-4z"/></g></svg>';
			break;
		case 'unsubscribe':
			$svg = '<svg class="genericon genericon-unsubscribe" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M15 9h-5c-.6 0-1 .4-1 1v5c0 .6.4 1 1 1h5c.6 0 1-.4 1-1v-5c0-.6-.4-1-1-1zm0 4h-5v-1h5v1zm-3-5V5c0-1.1-.9-2-2-2H2C.9 3 0 3.9 0 5v5c0 1.1.9 2 2 2h6v-2c0-1.2.8-2 2-2h2zM6 9.1L1 6.2V5l5 2.9L11 5v1.2L6 9.1z"/></g></svg>';
			break;
		case 'unzoom':
			$svg = '<svg class="genericon genericon-unzoom" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M4 6v1h5V6H4zm7 3.6c.6-.9 1-2 1-3.1C12 3.5 9.5 1 6.5 1S1 3.5 1 6.5 3.5 12 6.5 12c1.2 0 2.2-.4 3.1-1l3.7 3.7 1.4-1.4L11 9.6zm-4.5.9c-2.2 0-4-1.8-4-4s1.8-4 4-4 4 1.8 4 4-1.8 4-4 4z"/></g></svg>';
			break;
		case 'user':
			$svg = '<svg class="genericon genericon-user" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M8 8c1.7 0 3-1.3 3-3S9.7 2 8 2 5 3.3 5 5s1.3 3 3 3zm2 1H6c-1.7 0-3 1.3-3 3v2h10v-2c0-1.7-1.3-3-3-3z"/></g></svg>';
			break;
		case 'video':
			$svg = '<svg class="genericon genericon-video" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M12 4v1h-1V4H5v1H4V4H2v9h2v-1h1v1h6v-1h1v1h2V4h-2zm-7 7H4v-1h1v1zm0-2H4V8h1v1zm0-2H4V6h1v1zm7 4h-1v-1h1v1zm0-2h-1V8h1v1zm0-2h-1V6h1v1z"/></g></svg>';
			break;
		case 'videocamera':
			$svg = '<svg class="genericon genericon-videocamera" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M10 7V6c0-1.1-.9-2-2-2H4c-1.1 0-2 .9-2 2v4c0 1.1.9 2 2 2h4c1.1 0 2-.9 2-2V9l2.3 2.3c.6.6 1.7.2 1.7-.7V5.4c0-.9-1.1-1.3-1.7-.7L10 7z"/></g></svg>';
			break;
		case 'warning':
			$svg = '<svg class="genericon genericon-warning" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M15.6 11.3L9.7 1.6C8.8.1 7.3.1 6.4 1.6L.5 11.3C-.5 12.8.2 14 1.9 14h12.2c1.7 0 2.4-1.2 1.5-2.7zM8 12c-.6 0-1-.4-1-1s.4-1 1-1 1 .4 1 1-.4 1-1 1zm.8-3H7.2L7 4h2l-.2 5z"/></g></svg>';
			break;
		case 'website':
			$svg = '<svg class="genericon genericon-website" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M8 2C4.7 2 2 4.7 2 8s2.7 6 6 6 6-2.7 6-6-2.7-6-6-6zm3.9 3.8h-1.5c-.1-.7-.2-1.3-.4-1.8.7.3 1.4 1 1.9 1.8zm.6 2.2c0 .3 0 .5-.1.8h-1.9V8v-.8h1.9c.1.3.1.5.1.8zM8 12.5c-.2-.2-.6-.9-.8-2.2h1.6c-.2 1.2-.6 2-.8 2.2zM7 8.8V8v-.8h2v1.6H7zM3.5 8c0-.3 0-.5.1-.8h1.9v1.6H3.6c-.1-.3-.1-.5-.1-.8zM8 3.5c.2.1.6.9.8 2.2H7.2c.2-1.3.6-2.1.8-2.2zm-1.9.4c-.2.6-.3 1.2-.4 1.9H4.1c.5-.8 1.2-1.5 2-1.9zm-2 6.3h1.5c.1.7.2 1.3.4 1.8-.7-.3-1.4-1-1.9-1.8zm5.8 1.9c.2-.5.3-1.1.4-1.8h1.5c-.4.7-1.1 1.4-1.9 1.8z"/></g></svg>';
			break;
		case 'week':
			$svg = '<svg class="genericon genericon-week" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M12 3h-1V2H9v1H7V2H5v1H4c-1.1 0-2 .9-2 2v6c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm-3.8 8H7.1l1.7-5H6V5h4.2l-2 6z"/></g></svg>';
			break;
		case 'xpost':
			$svg = '<svg class="genericon genericon-xpost" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M13 4c0-1.1-.9-2-2-2s-2 .9-2 2c0 .7.4 1.4 1 1.7V7c0 1.1-.9 2-2 2-.7 0-1.4.2-2 .6V5.7c.6-.3 1-1 1-1.7 0-1.1-.9-2-2-2s-2 .9-2 2c0 .7.4 1.4 1 1.7V14h2v-1c0-1.1.9-2 2-2 2.2 0 4-1.8 4-4V5.7c.6-.3 1-1 1-1.7zm-8-.8c.4 0 .8.3.8.8s-.4.8-.8.8-.8-.4-.8-.8.4-.8.8-.8zm6 1.6c-.4 0-.8-.3-.8-.8s.3-.8.8-.8.8.3.8.8-.4.8-.8.8z"/></g></svg>';
			break;
		case 'zoom':
			$svg = '<svg class="genericon genericon-zoom" height="16" width="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><g><path d="M7 4H6v2H4v1h2v2h1V7h2V6H7V4zm4 5.6c.6-.9 1-2 1-3.1C12 3.5 9.5 1 6.5 1S1 3.5 1 6.5 3.5 12 6.5 12c1.2 0 2.2-.4 3.1-1l3.7 3.7 1.4-1.4L11 9.6zm-4.5.9c-2.2 0-4-1.8-4-4s1.8-4 4-4 4 1.8 4 4-1.8 4-4 4z"/></g></svg>';
			break;
		default: 
			$svg = 'Need to specify a genericon';
			break;
	}

	return $svg;
}
